# 2021 Jun 28

* NPE in DeduceTypes2 2096
    * Fixed at bbbebb2117c4a1bdcd4c0f13ea4cbebc6f7915c7

* ResolveError looking up named constructor
    * Fixed in 3caf3d739ce0b1e13ff52574ed014d6512dce9af
    
* NPE in WlGenerateFunction.java:43
    * Don't know where fixed at
    
* testDemoElNormalFact1Elijah: Not all hooks ran @ TestGenFunction.java:201
    * Fixed at a88dbeb574262bb08cc67b10d0fa4d67afcdde51 and 8fe5dd238ee2d68ec483a046ef0b03ed50452666 and 1d27a0cdf0db1d4d73438bcba4c801e527056511  

```
java.lang.NullPointerException
	at tripleo.elijah.stages.gen_fn.GeneratedClass.getName(GeneratedClass.java:78)
	at tripleo.elijah.stages.gen_c.GenerateC.generate_class(GenerateC.java:186)
	at tripleo.elijah.stages.gen_fn.TestGenFunction.testBasic1Backlink1Elijah(TestGenFunction.java:329)
```
* NPE    
    * Fixed at c243d617c264d13cd9d70be5a120a336236cffe5
    
```
java.lang.NullPointerException
	at tripleo.elijah.stages.gen_fn.WlGenerateFunction.run(WlGenerateFunction.java:43)
	at tripleo.elijah.work.WorkManager.drain(WorkManager.java:55)
	at tripleo.elijah.stages.deduce.DeduceTypes2$Lookup_function_on_exit.action(DeduceTypes2.java:701)
```
* NPE
    * Don't know where this was fixed at
    * This stops many tests from completing
    
```
[main] ERROR org.jdeferred2.impl.DefaultCallbackExceptionHandler - An uncaught exception occurred in DONE_CALLBACK
java.lang.NullPointerException
	at tripleo.elijah.stages.gen_fn.GenType.set(GenType.java:41)
	at tripleo.elijah.stages.deduce.DeducePhase$1.onDone(DeducePhase.java:413)
```
* NPE
    * Don't know where this is fixed at
    * Must have the following line at TestBasic line 69 to pass
        
```java
		Assert.assertEquals(10, (int)errorCount.get(1));
```

I'm not going to spend all day debugging things that already work, so I will just comment on the output I got.

Only for listfolders3, wprust.demo.fact and listfolders4.

### listFolders3

#### Main

1. The same problems from [Jun 26](1000-Jun26.md)
2. `MainLogic` appears in the clear, when it should be mangled
3. `MainLogic` itself is not being generated

#### Prelude

4. `arguments`: TTE is still not being recognized
5. also `arguments`: but argument count is being recognized as a member of the class now
6. Two namespaces are generated

### listfolders4

7. `listfolders4` has no changes

#### Prelude

8. `argument_count` is being recognized
9. Two namespaces are being generated
10. TTE is still not being resolved

### main2 (wprust.demo.fact)

These are the same problems from [Jun26](1000-Jun26.md) (except for #1 in `fact1.c`) but just copied over to here:

#### Main.c

10. `b1` is not deduced, but is assigned `(type Z0*)`
11. `z0argument`: can't find `Arguments` class code
12. `vt1` is not declared
13. `a1.isInt` is UNKKNOWN, `a1.toInt` is UNKNOWN
14. `f1` is not deduced, but is assigned (type `Z0*`)
15. `factorial_r` does not have `self` argument
16. `z0println`: can't find namespace class code
17. calling `z0println` with primitive

#### fact1.c

18. TTE not resolved for `Result`, but is a `USER_CLASS` now
19. method body not generated

